app_name: "NoMus"
version: "0.3.2"

#TODO: подумать: может быть лучше перенести в отдельный файл?
#Telegram bot lexicon
messages:
  uz:
    welcome: "NoMusga xush kelibsiz! Iltimos, harakatni tanlang:"
    error: "Xatolik yuz berdi."
    language_changed_prompt: "Til o'zgartirildi."
    confirm_phone_button: "Raqamimni tasdiqlang"
    share_phone_number_prompt: "Kontaktingizni ulashish uchun quyidagi tugmani bosing."
    start_ordering_button: "Buyurtma berish"
    registration_button: "Ro'yxatdan o'tish"
    cancel_button: "Bekor qilish"
    order_registration_prompt: "Buyurtma berish uchun avval ro'yxatdan o'tishingiz kerak. Iltimos, menyuda \"Ro'yxatdan o'tish\" tugmasini bosing."
    send_contact_button: "Kontaktni yuborish"
    send_contact_prompt: "Ro'yxatdan o'tish uchun aloqa ma'lumotlaringizni yuboring."
    share_location_prompt: "Iltimos, joylashuvingizni ulashing."
    share_location_button: "Joylashuvni ulashish"
    send_code_as_text_prompt: "Iltimos, kodni SMS orqali yuboring."
    code_sent_prompt: "Tasdiqlash kodi yuborildi (konsolga qarang). 4 ta raqamni kiriting:"
    enter_4_digits_prompt: "Iltimos, 4 ta raqamni kiriting."
    registration_successful: "Ro'yxatdan o'tish muvaffaqiyatli yakunlandi!"
    select_tariff_prompt: "Endi siz birinchi buyurtmangizni berishingiz mumkin. Rejani tanlang:"
    phone_number_error: "Telefon raqamini olib bo'lmadi. Qaytadan urinib ko'ring."
    invalid_code_error: "Noto'g'ri kod. Iltimos, qaytadan urinib ko'ring."
    choose_tariff_from_list_prompt: "Iltimos, ro'yxatdan tarifni tanlang."
    payment_button: "To'lash {amount} sum"
    payment_prompt: "Siz {tariff_name} tarifini tanladingiz. To'lanishi kerak bo'lgan summa: {amount}"
    payment_processing: "To'lov amalga oshirilmoqda…"
    order_success: "Buyurtma #{order_id} muvaffaqiyatli to'landi va yaratildi!"
    payment_error: "To'lov xatosi."
    user_agreement_prompt: "Пожалуйста, ознакомьтесь и примите условия:"
    user_agreement_button: "Foydalanuvchi shartnomasi"
    user_agreement_accept_button: "Roziman"
    user_agreement_url: "https://docs.google.com/document/d/e/2PACX-1vTJwhwg6mWX5JSw4G3e2rh7sJ6K48oKYa_gaCq9pBnFP3FYCnI-mLUYLpJxWwkaQC55IDAuMuVSL7J_/pub"
    agree_button: "Roziman"
  en:
    welcome: "Welcome to NoMus! Please choose an action:"
    error: "An error occurred."
    language_changed_prompt: "Language changed."
    confirm_phone_button: "Confirm my number"
    share_phone_number_prompt: "Click the button below to share your contact."
    start_ordering_button: "Make an order"
    registration_button: "Registration"
    cancel_button: "Cancel"
    order_registration_prompt: "To make an order, you need to register first. Please press 'Registration' in the menu."
    send_contact_button: "Send contact"
    send_contact_prompt: "Please send your contact information for registration."
    share_location_prompt: "Please share your location."
    share_location_button: "Share location"
    send_code_as_text_prompt: "Please send the code as a text message."
    code_sent_prompt: "The verification code has been sent (see console). Enter the 4 digits:"
    enter_4_digits_prompt: "Please enter 4 digits."
    registration_successful: "Registration completed successfully!"
    select_tariff_prompt: "Now you can place your first order. Choose a plan:"
    phone_number_error: "Unable to retrieve phone number. Please try again."
    invalid_code_error: "Invalid code. Please try again."
    choose_tariff_from_list_prompt: "Please select a tariff from the list."
    payment_button: "Pay {amount} sum"
    payment_prompt: "You have selected the {tariff_name} tariff. Amount due: {amount}"
    payment_processing: "Processing payment..."
    order_success: "The order #{order_id} has been successfully paid and created!"
    payment_error: "Payment error."
    user_agreement_prompt: "Please read and agree to the terms:"
    user_agreement_button: "User agreement"
    user_agreement_accept_button: "Agree"
    user_agreement_url: "https://docs.google.com/document/d/e/2PACX-1vQdDZY4lJwZ0FWOIbF5Gvduj9zDcMSFdeypzeYr6IjXOvLLkSmotk0FMr3ziOMdzhIraL9ZDKLRFh13/pub"
    agree_button: "Agree"
  ru:
    welcome: "Добро пожаловать в NoMus! Выберите действие:"
    error: "Произошла ошибка."
    language_changed_prompt: "Язык изменен."
    confirm_phone_button: "Подтвердить мой номер"
    share_phone_number_prompt: "Нажмите кнопку ниже, чтобы поделиться своим контактом."
    start_ordering_button: "Сделать заказ"
    registration_button: "Регистрация"
    cancel_button: "Отменить"
    order_registration_prompt: "Чтобы сделать заказ, вам необходимо сначала зарегистрироваться. Нажмите 'Регистрация' в меню."
    send_contact_button: "Отправить контакт"
    send_contact_prompt: "Пожалуйста, отправьте ваш контакт для регистрации."
    share_location_prompt: "Пожалуйста, поделитесь своим местоположением."
    share_location_button: "Поделиться местоположением"
    send_code_as_text_prompt: "Пожалуйста, отправьте код в виде текстового сообщения."
    code_sent_prompt: "Код подтверждения отправлен (см. консоль). Введите 4 цифры:"
    enter_4_digits_prompt: "Пожалуйста, введите 4 цифры."
    registration_successful: "Регистрация успешно завершена!"
    select_tariff_prompt: "Теперь вы можете сделать свой первый заказ. Выберите тариф:"
    phone_number_error: "Не удалось получить номер телефона. Попробуйте еще раз."
    invalid_code_error: "Неверный код. Попробуйте еще раз."
    choose_tariff_from_list_prompt: "Пожалуйста, выберите тариф из списка."
    payment_button: "Оплатить {amount} сум"
    payment_prompt: "Вы выбрали тариф {tariff_name}. Сумма к оплате: {amount}"
    payment_processing: "Обработка платежа..."
    order_success: "Заказ #{order_id} успешно оплачен и создан!"
    payment_error: "Ошибка оплаты."
    user_agreement_prompt: "Пожалуйста, ознакомьтесь и примите условия:"
    user_agreement_button: "Пользовательское соглашение"
    user_agreement_accept_button: "Согласен"
    user_agreement_url: "https://docs.google.com/document/d/e/2PACX-1vSSiwrImDdqZE8GDIH_K1D8tb8LYs3crheTTfzmkdMKVgCxM1XNgfenN9dG_FQULEkpMXoZZIQGLDc_/pub"
    agree_button: "Согласен"

